""" 
Performance metrics for pairs trading backtests.

This module contains functions for computing return, risk, drawdown,
turnover, transaction cost, and statistical significance diagnostics
from strategy return series generated by backtest.py.

It does not generate trading signals, estimate hedge ratios, compute spreads,
or select pairs. It assumes strategy returns and position series have already
been created by the backtest module.

Newey-West adjusted t-statistics are included because daily strategy returns
may exhibit autocorrelation and heteroskedasticity.

Metrics included:
cumulative return, annualized return, mean daily return, annualized volatility,
annualized sharpe ratio, drawdown series, maximum drawdown, hit rate, number of 
position changes, turnover, total transaction costs, Newey-West adjusted 
mean return t-stat, Newey-West pvalue.
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm

def _validate_returns(
    strategy_returns
):
    
    #strategy_returns is a pandas Series
    if not isinstance(strategy_returns, pd.Series):
        raise TypeError("strategy_returns should be a pandas Series.")
    
    #strategy_returns is not empty
    if strategy_returns.empty:
        raise ValueError("strategy_returns should not be empty.")
    
    #drop Nans
    strategy_returns = strategy_returns.dropna()
    
    #check if still not empty
    if strategy_returns.empty:
        raise ValueError("strategy_returns should not be empty after dropping missing values..")
    
    #strategy_returns has numeric values
    if not pd.api.types.is_numeric_dtype(strategy_returns):
        raise TypeError("strategy_returns should have numeric values.")
    
    return strategy_returns

def compute_cumulative_returns(
    strategy_returns
):
    
    #Validate strategy_returns
    strategy_returns = _validate_returns(strategy_returns)
    
    #Calculate cumulative returns
    cumulative_returns = (1+strategy_returns).cumprod() - 1
    cumulative_returns.name =  "cumulative_return"
    
    return cumulative_returns

def compute_mean_daily_return(
    strategy_returns
):
    
    #Validate strategy_returns
    strategy_returns = _validate_returns(strategy_returns)
    
    #Calculate mean daily return
    mean_daily_return = strategy_returns.mean()
    
    return mean_daily_return

def compute_annualized_return(
    strategy_returns,
    periods_per_year = 252
):
    
    #Validate strategy_returns and periods_per_year
    strategy_returns = _validate_returns(strategy_returns)
    if not isinstance(periods_per_year,(int,float,np.number)):
        raise TypeError("periods_per_year should be numeric.")
    
    if periods_per_year <=0:
        raise ValueError("periods_per_year should be a positive number.")
    
    #Count observations
    n_periods = strategy_returns.shape[0]
    
    #Compute total growth
    total_growth = (1 + strategy_returns).cumprod().iloc[-1]
    
    #Calculate number of years
    n_years = n_periods / periods_per_year
    
    #Calculate annualized return
    annualized_return = total_growth ** (1/n_years) -1
    
    return annualized_return

def compute_annualized_volatility(
    strategy_returns,
    periods_per_year = 252
):
    
    #Validate strategy_returns and periods_per_year
    strategy_returns = _validate_returns(strategy_returns)
    if not isinstance(periods_per_year,(int,float,np.number)):
        raise TypeError("periods_per_year should be numeric.")
    
    if periods_per_year <=0:
        raise ValueError("periods_per_year should be a positive number.")
    
    #Calculate annualized volatility
    daily_volatility = strategy_returns.std()
    annualized_volatility = daily_volatility * np.sqrt(periods_per_year)
    
    return annualized_volatility

def compute_sharpe_ratio(
    strategy_returns,
    periods_per_year = 252,
    risk_free_rate = 0.0
):
    
    #Validate strategy_returns and periods_per_year
    strategy_returns = _validate_returns(strategy_returns)
    if not isinstance(periods_per_year,(int,float,np.number)):
        raise TypeError("periods_per_year should be numeric.")
    
    if periods_per_year <=0:
        raise ValueError("periods_per_year should be a positive number.")
    
    #Validate the risk-free rate
    if not isinstance(risk_free_rate,(int,float,np.number)):
        raise TypeError("risk_free_rate should be numeric.")
        
    #Calculate annualized_return and annualized_volatility
    annualized_volatility = compute_annualized_volatility(strategy_returns, periods_per_year)
    annualized_return = compute_annualized_return(strategy_returns, periods_per_year)
    
    if annualized_volatility == 0 or np.isnan(annualized_volatility):
        return np.nan
    
    sharpe_ratio = (annualized_return - risk_free_rate) / annualized_volatility
    
    return sharpe_ratio

def compute_drawdown(
    strategy_returns
):
    
    #Validate strategy_returns
    strategy_returns = _validate_returns(strategy_returns)
    
    #calculate drawdown
    wealth_index = (1 + strategy_returns).cumprod()
    running_max = wealth_index.cummax()
    
    drawdown = wealth_index / running_max -1
    drawdown.name = "drawdown"
    
    return drawdown

def compute_max_drawdown(
    strategy_returns
):
    
    #obtain drawdown and maximum drawdown
    drawdown = compute_drawdown(strategy_returns)
    max_drawdown = drawdown.min()
    
    return max_drawdown

def compute_hit_rate(
    strategy_returns
):
    
    #Validate strategy returns
    strategy_returns = _validate_returns(strategy_returns)
    
    #Calculating hit rate
    #For V1, zero returns days are NOT treated as win days
    hit_rate = (strategy_returns > 0).sum()/len(strategy_returns)
    
    return hit_rate

def compute_position_changes(
    positions
):
    
    #Validate that positions is a non-empty pandas Series
    if not isinstance(positions, pd.Series):
        raise TypeError("positions should be a pandas Series.")
    
    if positions.empty:
        raise ValueError("positions should not be empty.")
    
    #Check that positions has no NaNs and only contains -1, 0, or 1.
    if pd.isna(positions).any():
        raise ValueError("positions cannot have NaNs.")
    
    if not (positions.isin([-1,0,1])).all():
        raise ValueError("positions can only contain -1, 0, or 1.")
    
    #Compute position changes
    position_changes = positions.diff().abs().fillna(0)
    
    return position_changes

def compute_number_of_position_changes(
    positions
):
    
    #Compute position changes
    position_changes = compute_position_changes(positions)
    
    #Compute number of position changes
    number_of_position_changes = (position_changes >0).sum()
    
    return number_of_position_changes

def compute_turnover(
    positions
    ):
    
    #Compute position changes
    position_changes = compute_position_changes(positions)
    
    #Compute turnover
    turnover = position_changes.sum()
    
    return turnover

def compute_total_transaction_costs(
    transaction_costs
):
    
    """ 
    This function is a summation of total transaction costs. In V1, this is a simple
    spread level cost. In V2, this would be expanded to account for slippage, leg
    level costs, taxes, commissions, etc.
    """
    #Validate transaction costs as a non-empty pandas Series
    if not isinstance(transaction_costs, pd.Series):
        raise TypeError("transaction_costs should be a pandas Series.")
    
    if transaction_costs.empty:
        raise ValueError("transaction_costs should not be empty.")
    
    #Handling any NaNs
    transaction_costs = transaction_costs.dropna()
    
    if transaction_costs.empty:
        raise ValueError("transaction_costs should not be empty after dropping NaN.")
    
    if not pd.api.types.is_numeric_dtype(transaction_costs):
        raise TypeError("The transaction_costs values should be numeric.")
    
    if (transaction_costs < 0).any():
        raise ValueError("transaction_costs should be nonnegative.")
    
    total_transaction_cost = transaction_costs.sum()
    
    return total_transaction_cost

def compute_newey_west_tstat(
    strategy_returns,
    lags = 5,
    periods_per_year = 252
):
    
    #Validate strategy_returns
    strategy_returns = _validate_returns(strategy_returns)
    
    #lags is an integer and nonnegative
    if not isinstance(lags,(int,np.integer)):
        raise TypeError("lags must be an integer.")
    
    if lags < 0:
        raise ValueError("lags must be nonnegative.")
    
    #periods_per_year is numeric and positive
    if not isinstance(periods_per_year,(int,np.number)):
        raise TypeError("periods_per_year must be numeric.")
    
    if periods_per_year <= 0:
        raise ValueError("periods_per_year must be positive.")
    
    #set y as cleaned strategy returns and x as constant only
    y  = strategy_returns
    x = pd.DataFrame(
        {"const": 1.0},
        index=y.index
        )
    
    if y.shape[0] <= lags+1:
        raise ValueError("There are too few observations for the tstat.")
    
    #Fit OLS with HAC / Newey West covariance
    model = sm.OLS(y,x).fit(cov_type='HAC', cov_kwds={"maxlags":lags})
    
    #Extract alpha, annualized_alpha, tstat, pvalue, standard error
    alpha = model.params['const']
    annualized_alpha = alpha*periods_per_year
    newey_west_standard_error = model.bse["const"]
    newey_west_tstat = model.tvalues["const"] 
    newey_west_pvalue = model.pvalues["const"]  
    
    reg_summary = {
        "alpha":alpha,
        "annualized_alpha":annualized_alpha,
        "newey_west_standard_error":newey_west_standard_error,
        "newey_west_tstat":newey_west_tstat,
        "newey_west_pvalue":newey_west_pvalue,
        "lags":lags,
        "n_observations":len(y)
    } 
    
    return reg_summary

def summarize_backtest_performance(
    backtest_df,
    periods_per_year = 252,
    risk_free_rate = 0.0,
    newey_west_lags = 5
):
    
    #Summarize and return a dictionary with all functions
    
    #Validate backtest_df
    if not isinstance(backtest_df, pd.DataFrame):
        raise TypeError("backtest_df should be a pandas DataFrame.")
    
    if backtest_df.empty:
        raise ValueError("backtest_df should not be empty.")
    
    if not "strategy_return" in backtest_df:
        raise ValueError("backtest_df must contain strategy_returns.")
    
    if not "position" in backtest_df:
        raise ValueError("backtest_df must contain positions.")
    
    if not "transaction_cost" in backtest_df:
        raise ValueError("backtest_df must contain transaction_costs.")
    
    #Extract the series
    strategy_returns = backtest_df["strategy_return"]
    positions = backtest_df["position"]
    transaction_costs = backtest_df["transaction_cost"]
    
    #Obtain return metrics
    cumulative_returns = compute_cumulative_returns(strategy_returns)
    final_cumulative_return = cumulative_returns.iloc[-1]
    mean_daily_return = compute_mean_daily_return(strategy_returns)
    annualized_return = compute_annualized_return(strategy_returns, periods_per_year)
    
    #Risk metrics
    annualized_volatility = compute_annualized_volatility(strategy_returns, periods_per_year)
    sharpe_ratio = compute_sharpe_ratio(strategy_returns, periods_per_year, risk_free_rate)
    max_drawdown = compute_max_drawdown(strategy_returns)
    
    #Trading diagnostics
    hit_rate = compute_hit_rate(strategy_returns)
    number_of_position_changes = compute_number_of_position_changes(positions)
    turnover = compute_turnover(positions)
    total_transaction_costs = compute_total_transaction_costs(transaction_costs)
    
    #Statistical significance
    newey_west_summary = compute_newey_west_tstat(strategy_returns, newey_west_lags, periods_per_year)
    
    #Summary dictionary
    results = {
        "n_observations":len(_validate_returns(strategy_returns)),
        "final_cumulative_return":final_cumulative_return,
        "mean_daily_return":mean_daily_return,
        "annualized_return":annualized_return,
        "annualized_volatility":annualized_volatility,
        "sharpe_ratio":sharpe_ratio,
        "max_drawdown":max_drawdown,
        "hit_rate":hit_rate,
        "number_of_position_changes":number_of_position_changes,
        "turnover":turnover,
        "total_transaction_costs":total_transaction_costs,
        "alpha":newey_west_summary["alpha"],
        "annualized_alpha":newey_west_summary["annualized_alpha"],
        "newey_west_standard_error":newey_west_summary["newey_west_standard_error"],
        "newey_west_tstat":newey_west_summary["newey_west_tstat"],
        "newey_west_pvalue":newey_west_summary["newey_west_pvalue"],
        "newey_west_lags":newey_west_lags
    }
    
    return results

def summarize_return_series_performance(
    strategy_returns,
    fold_id=None,
    weight_method=None,
    periods_per_year=252,
    risk_free_rate=0.0,
    newey_west_lags=5,
):
    
    strategy_returns = _validate_returns(strategy_returns)
    
    cumulative_returns = compute_cumulative_returns(strategy_returns)
    
    try:
        newey_west_summary = compute_newey_west_tstat(
            strategy_returns=strategy_returns,
            lags=newey_west_lags,
            periods_per_year=periods_per_year
        )
        
    except ValueError:
        newey_west_summary = {
            "alpha":np.nan,
            "annualized_alpha":np.nan,
            "newey_west_standard_error":np.nan,
            "newey_west_tstat":np.nan,
            "newey_west_pvalue":np.nan
        }
    
    return {
        "fold_id": fold_id,
        "weight_method": weight_method,
        "start_date": strategy_returns.index.min(),
        "end_date": strategy_returns.index.max(),
        "n_observations": len(strategy_returns),
        "final_cumulative_return": cumulative_returns.iloc[-1],
        "mean_daily_return": compute_mean_daily_return(strategy_returns),
        "annualized_return": compute_annualized_return(strategy_returns, periods_per_year),
        "annualized_volatility": compute_annualized_volatility(strategy_returns, periods_per_year),
        "sharpe_ratio": compute_sharpe_ratio(
            strategy_returns,
            periods_per_year=periods_per_year,
            risk_free_rate=risk_free_rate,
        ),
        "max_drawdown": compute_max_drawdown(strategy_returns),
        "hit_rate": compute_hit_rate(strategy_returns),
        "alpha": newey_west_summary["alpha"],
        "annualized_alpha": newey_west_summary["annualized_alpha"],
        "newey_west_standard_error": newey_west_summary["newey_west_standard_error"],
        "newey_west_tstat": newey_west_summary["newey_west_tstat"],
        "newey_west_pvalue": newey_west_summary["newey_west_pvalue"],
        "newey_west_lags": newey_west_lags
    }

def summarize_portfolio_by_fold(
    portfolio_returns_by_fold,
    periods_per_year = 252,
    risk_free_rate = 0.0,
    newey_west_lags = 5
):
    
    if not isinstance(portfolio_returns_by_fold, dict):
        raise TypeError("portfolio_returns_by_fold should be a dictionary.")
    
    records = []
    
    for fold_id, portfolio_returns_df in portfolio_returns_by_fold.items():
        if not isinstance(portfolio_returns_df,pd.DataFrame):
            raise TypeError("portfolio_returns_df should be a pandas DataFrame.")
        
        if portfolio_returns_df.empty:
            raise ValueError("portfolio_returns_df should not be empty.")
        
        for weight_method in portfolio_returns_df.columns:
            metrics = summarize_return_series_performance(
                portfolio_returns_df[weight_method],
                fold_id=fold_id,
                weight_method=weight_method,
                periods_per_year=periods_per_year,
                risk_free_rate=risk_free_rate,
                newey_west_lags=newey_west_lags,
            )
            
            records.append(metrics)
    
    return pd.DataFrame(records)